repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # Identify invalid files
  - id: check-yaml
  - id: check-json
  # git checks
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-case-conflict
  # Python checks
  - id: check-docstring-first
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
  - id: fix-byte-order-marker
  # General quality checks
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer

# - repo: https://github.com/PyCQA/isort
#   rev: 5.10.1
#   hooks:
#   -  id: isort

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
