name: Analyze-Code

on:
    workflow_run:
        workflows: ['CI']
        branches: [main]
        types:
            - completed

jobs:
    analyze:
        name: Analyze code
        runs-on: ubuntu-latest
        permissions:
          actions: read
          contents: read
          security-events: write

        strategy:
          fail-fast: false
          matrix:
            language: [ 'typescript', 'python' ]

        steps:
        - name: Checkout source code
          uses: actions/checkout@v4.1.2

        - name: Initialize CodeQL
          uses: github/codeql-action/init@v3
          with:
            languages: ${{ matrix.language }}

        - name: Autobuild
          uses: github/codeql-action/autobuild@v3

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
