name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
        - name: Checkout source code
          uses: actions/checkout@v4.1.2

        - name: Setup python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: '3.9'

        - name: Install
          run: make install

        - name: Setup node
          uses: actions/setup-node@v4.0.2
          with:
            node-version-file: './client/.nvmrc'
            cache: npm

        - name: Install pre-commit
          run: pip3 install pre-commit

        - name: Run pre-commit
          run: pre-commit run --all-files --show-diff-on-failure --color always

        - name: Run server tests
          run: make test-server

        - name: Install client
          run: make install-client

        - name: Run client tests
          run: make test-client-ci
