name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source code
          uses: actions/checkout@v4.1.2

        - name: Setup python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.9'

        - name: Install server
          run: make install

        - name: Run server tests
          run: make test-server

