name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains( github.event.head_commit.message, 'pre-commit') }}
    timeout-minutes: 10
    steps:
        - name: Checkout source code
          uses: actions/checkout@v4.1.2

        - name: Setup python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: '3.9'

        - name: Setup node
          uses: actions/setup-node@v4.0.2
          with:
            node-version-file: './client/.nvmrc'

        - name: Install server
          run: make install

        - name: Install client
          run: make install-client

        - name: Cache pre-commit
          uses: actions/cache@v3.3.3
          with:
            path: ~/.cache/pre-commit
            key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

        - name: Install pre-commit
          run: pip3 install pre-commit

        - name: Run pre-commit
          run: pre-commit run --all-files --show-diff-on-failure --color always

  build-and-run-tests:
    runs-on: ubuntu-latest
    if: |
      always() &&
      (needs.pre-commit.result == 'success' || needs.pre-commit.result == 'skipped')
    needs: pre-commit
    timeout-minutes: 10
    steps:
        - name: Checkout source code
          uses: actions/checkout@v4.1.2

        - name: Setup python
          uses: actions/setup-python@v5.1.0
          with:
            python-version: '3.9'

        - name: Setup node
          uses: actions/setup-node@v4.0.2
          with:
            node-version-file: './client/.nvmrc'

        - name: Install server
          run: make install

        - name: Install client
          run: make install-client

        - name: Run server tests
          run: make test-server

        - name: Run client tests
          run: make test-client-ci
